postsubmits:
  ouzi-dev/bigbang:
    - name: release-bigbang
      decorate: true 
      max_concurrency: 1 
      labels:
        preset-semantic-release: "true"      
      branches:
        - master
      spec: 
        containers:
          - name: "release-bigbang"
            imagePullPolicy: IfNotPresent
            image: quay.io/ouzi/go-builder:1.13.1
            command:
              - make
            args:
              - semantic-release
