presubmits:
  ouzi-dev/prow-helm-chart:
    - name: test-prow-helm-chart-lint
      context: test-prow-helm-chart-lint
      decorate: true 
      always_run: true 
      skip_report: false 
      max_concurrency: 1 
      trigger: "(?m)lint( please)?" 
      rerun_command: "test"
      spec: 
        containers:
          - name: "test-prow-helm-chart-lint"
            imagePullPolicy: IfNotPresent
            image: quay.io/ouzi/go-builder:1.13.1
            command:
              - make
            args:
              - lint
    - name: test-prow-helm-chart-validate
      context: test-prow-helm-chart-validate
      decorate: true 
      always_run: true 
      skip_report: false 
      max_concurrency: 1 
      trigger: "(?m)validate( please)?" 
      rerun_command: "test"
      spec: 
        containers:
          - name: "test-prow-helm-chart-validate"
            imagePullPolicy: IfNotPresent
            image: quay.io/ouzi/go-builder:1.13.1
            command:
              - make
            args:
              - validate
postsubmits:
  ouzi-dev/prow-prow-helm-chart:
    - name: release-prow-helm-chart
      decorate: true 
      max_concurrency: 1 
      labels:
        preset-semantic-release: "true"      
      branches:
        - master
      spec: 
        containers:
          - name: "release-prow-helm-chart"
            imagePullPolicy: IfNotPresent
            image: quay.io/ouzi/go-builder:1.13.1
            command:
              - make
            args:
              - semantic-release