---
apiVersion: credstash.ouzi.tech/v1alpha1
kind: CredstashSecret
metadata:
  name: preemptible-killer-secrets
  namespace: {{ .namespace }}
spec:
  secrets:
  - name: google-service-account.json
    key: {{ .service_account.credstash.key | quote }}
    table: {{ .service_account.credstash.table | quote }}
    version: {{ .service_account.credstash.version | quote }}

