presubmits:
  ouzi-dev/avro-kedavro:
    # https://github.com/kubernetes/test-infra/blob/master/prow/inrepoconfig.md
    - name: validate-prow-yaml
      always_run: true
      decorate: true
      clone_uri: "git@github.com:ouzi-dev/avro-kedavro.git"
      trigger: "(?m)validate-prow-yaml( please)?"
      rerun_command: "validate-prow-yaml"
      extra_refs:
        - org: ouzi-dev
          repo: test-infra
          base_ref: master
      spec:
        tolerations:
          - effect: NoSchedule
            key: cloud.google.com/gke-preemptible
            operator: Equal
            value: "true"
        containers:
          - image: gcr.io/k8s-prow/checkconfig:v20200610-6c96a0a6ed
            command:
              - /app/prow/cmd/checkconfig/app.binary
            args:
              - --plugin-config=../test-infra/prow/plugins.yaml
              - --config-path=../test-infra/prow/config.yaml
              - --prow-yaml-repo-name=$(REPO_OWNER)/$(REPO_NAME)
    - name: validate-no-creds
      always_run: true
      decorate: true
      clone_uri: "git@github.com:ouzi-dev/avro-kedavro.git"
      trigger: "(?m)validate-no-creds( please)?"
      rerun_command: "validate-no-creds"
      spec:
        tolerations:
          - effect: NoSchedule
            key: cloud.google.com/gke-preemptible
            operator: Equal
            value: "true"
        containers:
          - image: quay.io/ouzi/git-secret-scanner:0.0.3
            command:
              - git-secrets
            args:
              - --scan
    - name: test-avro-kedavro
      context: test-avro-kedavro
      decorate: true
      clone_uri: "git@github.com:ouzi-dev/avro-kedavro.git"
      always_run: true
      skip_report: false
      max_concurrency: 1
      trigger: "(?m)test( please)?"
      rerun_command: "test"
      spec:
        tolerations:
          - effect: NoSchedule
            key: cloud.google.com/gke-preemptible
            operator: Equal
            value: "true"
        containers:
          - name: "test-avro-kedavro"
            imagePullPolicy: IfNotPresent
            image: quay.io/ouzi/go-builder:1.14.2
            command:
              - make
            args:
              - test
postsubmits:
  ouzi-dev/avro-kedavro:
    - name: release-avro-kedavro
      decorate: true
      clone_uri: "git@github.com:ouzi-dev/avro-kedavro.git"
      max_concurrency: 1
      branches:
        - master
      spec:
        tolerations:
          - effect: NoSchedule
            key: cloud.google.com/gke-preemptible
            operator: Equal
            value: "true"
        containers:
          - name: "release-avro-kedavro"
            imagePullPolicy: IfNotPresent
            image: quay.io/ouzi/go-builder:1.14.2
            command:
              - make
            args:
              - semantic-release
            env:
              - name: GITHUB_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: github-token
                    key: oauth
