---
apiVersion: credstash.ouzi.tech/v1alpha1
kind: CredstashSecret
metadata:
  name: github-oauth-secret
  namespace: {{ .namespace }}
spec:
  secrets:
  - name: client-id
    key: {{ .credstash.oauthproxy_clientid.key | quote }}
    table: {{ .credstash.oauthproxy_clientid.table | quote }}
    version: {{ .credstash.oauthproxy_clientid.version | quote}}
  - name: client-secret
    key: {{ .credstash.oauthproxy_clientsecret.key | quote }}
    table: {{ .credstash.oauthproxy_clientsecret.table | quote }}
    version: {{ .credstash.oauthproxy_clientsecret.version | quote }}
  - name: cookie-secret
    key: {{ .credstash.oauthproxy_cookiesecret.key | quote }}
    table: {{ .credstash.oauthproxy_cookiesecret.table | quote }}
    version: {{ .credstash.oauthproxy_cookiesecret.version | quote }}    