---
apiVersion: credstash.ouzi.tech/v1alpha1
kind: CredstashSecret
metadata:
  name: preemptible-killer-secrets
  namespace: {{ .namespace }}
spec:
  secrets:
  - name: google-service-account.json
    key: {{ .credstash.service_account.key | quote }}
    table: {{ .credstash.service_account.table | quote }}
    version: {{ .credstash.service_account.version | quote }}

