presubmits:
  ouzi-dev/test-infra:
    - name: test-prow-config
      context: test-prow-config
      decorate: true 
      clone_uri: "git@github.com:ouzi-dev/test-infra.git"
      always_run: false 
      skip_report: false 
      max_concurrency: 1 
      trigger: "(?m)test-prow-config( please)?" 
      rerun_command: "test-prow-config"
      run_if_changed: '^(config/.*|prow/.*)$'
      spec: 
        containers:
          - name: "test-config"
            imagePullPolicy: IfNotPresent
            command:
              - /app/prow/cmd/checkconfig/app.binary
            args:
              - --config-path=prow/config.yaml
              - --plugin-config=prow/plugins.yaml
              - --job-config-path=config/jobs
            image: gcr.io/k8s-prow/checkconfig:v20191028-a687a71be
    - name: monitoring-dry-run
      context: monitoring-dry-run
      decorate: true 
      clone_uri: "git@github.com:ouzi-dev/test-infra.git"
      always_run: false 
      skip_report: false 
      max_concurrency: 1
      trigger: "(?m)monitoring( please)?" 
      rerun_command: "monitoring"
      run_if_changed: 'monitoring/'
      spec: 
        serviceAccountName: prow
        containers:
          - name: "monitoring-dry-run"
            imagePullPolicy: IfNotPresent
            command:
              - make
            args:
              - monitoring-dry-run
            image: quay.io/ouzi/toolbox:helm-v2.14.3
postsubmits:
  ouzi-dev/test-infra:
    - name: test-config-postsubmit
      clone_uri: "git@github.com:ouzi-dev/test-infra.git"
      decorate: true
      max_concurrency: 1 
      run_if_changed: '^(config/.*|prow/.*)$'
      branches:
        - master
      spec:
        containers:
          - name: "test-config"
            imagePullPolicy: IfNotPresent
            command:
              - /app/prow/cmd/checkconfig/app.binary
            args:
              - --config-path=prow/config.yaml
              - --plugin-config=prow/plugins.yaml
              - --job-config-path=config/jobs
            image: gcr.io/k8s-prow/checkconfig:v20191028-a687a71be
    - name: monitoring
      decorate: true 
      clone_uri: "git@github.com:ouzi-dev/test-infra.git"
      max_concurrency: 1
      run_if_changed: 'monitoring/'
      branches:
        - master
      spec: 
        serviceAccountName: prow
        containers:
          - name: "monitoring"
            imagePullPolicy: IfNotPresent
            command:
              - make
            args:
              - monitoring-apply
            image: quay.io/ouzi/toolbox:helm-v2.14.3
