presubmits:
  ouzi-dev/test-infra:
    - name: test-prow-config
      context: test-prow-config
      decorate: true 
      clone_uri: "git@github.com:ouzi-dev/test-infra.git"
      always_run: false 
      skip_report: false 
      max_concurrency: 1 
      trigger: "(?m)test-prow-config( please)?" 
      rerun_command: "test-prow-config"
      run_if_changed: '^(config/.*|prow/.*)$'
      spec: 
        containers:
          - name: "test-config"
            imagePullPolicy: IfNotPresent
            command:
              - /app/prow/cmd/checkconfig/app.binary
            args:
              - --config-path=prow/config.yaml
              - --plugin-config=prow/plugins.yaml
              - --job-config-path=config/jobs
            image: gcr.io/k8s-prow/checkconfig:v20200131-19ad23dfd
    - name: monitoring-dry-run
      context: monitoring-dry-run
      decorate: true 
      clone_uri: "git@github.com:ouzi-dev/test-infra.git"
      always_run: false 
      skip_report: false 
      max_concurrency: 1
      trigger: "(?m)monitoring( please)?" 
      rerun_command: "monitoring"
      run_if_changed: 'monitoring/'
      spec: 
        serviceAccountName: prow
        containers:
          - name: "monitoring-dry-run"
            imagePullPolicy: IfNotPresent
            command:
              - make
            args:
              - monitoring-dry-run
            image: quay.io/ouzi/toolbox:0.1.9
    - name: test-infra
      context: test-infra
      decorate: true 
      clone_uri: "git@github.com:ouzi-dev/test-infra.git"
      always_run: false 
      skip_report: false 
      max_concurrency: 1
      labels:
        preset-aws-ouzi: "true"
      trigger: "(?m)test-infra( please)?" 
      rerun_command: "test-infra"
      run_if_changed: '^(infrastructure/.*)$'
      spec: 
        containers:
          - name: "test-infra"
            imagePullPolicy: IfNotPresent
            command:
              - make
            args:
              - infra-setup
              - infra-plan
            image: quay.io/ouzi/toolbox:0.1.9
    - name: test-manifests
      context: test-manifests
      decorate: true 
      clone_uri: "git@github.com:ouzi-dev/test-infra.git"
      always_run: false 
      skip_report: false 
      max_concurrency: 1
      labels:
        preset-aws-ouzi: "true"
      trigger: "(?m)test-manifests( please)?" 
      rerun_command: "test-manifests"
      run_if_changed: '^(cluster/.*)$'
      spec: 
        serviceAccountName: prow
        containers:
          - name: "test-manifests"
            imagePullPolicy: IfNotPresent
            command:
              - make
            args:
              -  deploy-dry-run
            image: quay.io/ouzi/toolbox:0.1.9
postsubmits:
  ouzi-dev/test-infra:
    - name: test-config-postsubmit
      clone_uri: "git@github.com:ouzi-dev/test-infra.git"
      decorate: true
      max_concurrency: 1 
      run_if_changed: '^(config/.*|prow/.*)$'
      branches:
        - master
      spec:
        containers:
          - name: "test-config"
            imagePullPolicy: IfNotPresent
            command:
              - /app/prow/cmd/checkconfig/app.binary
            args:
              - --config-path=prow/config.yaml
              - --plugin-config=prow/plugins.yaml
              - --job-config-path=config/jobs
            image: gcr.io/k8s-prow/checkconfig:v20200131-19ad23dfd
    - name: monitoring
      decorate: true 
      clone_uri: "git@github.com:ouzi-dev/test-infra.git"
      max_concurrency: 1
      run_if_changed: 'monitoring/'
      branches:
        - master
      spec: 
        serviceAccountName: prow
        containers:
          - name: "monitoring"
            imagePullPolicy: IfNotPresent
            command:
              - make
            args:
              - monitoring-apply
            image: quay.io/ouzi/toolbox:0.1.9
    - name: apply-infra
      context: apply-infra
      decorate: true 
      clone_uri: "git@github.com:ouzi-dev/test-infra.git"
      always_run: false 
      skip_report: false 
      max_concurrency: 1
      labels:
        preset-aws-ouzi: "true"
      trigger: "(?m)apply-infra( please)?" 
      rerun_command: "apply-infra"
      run_if_changed: '^(infrastructure/.*)$'
      branches:
        - master
      spec: 
        containers:
          - name: "apply-infra"
            imagePullPolicy: IfNotPresent
            command:
              - make
            args:
              - infra-setup
              - infra-apply
            image: quay.io/ouzi/toolbox:0.1.9
    - name: deploy-prow
      context: deploy-prow
      decorate: true 
      clone_uri: "git@github.com:ouzi-dev/test-infra.git"
      always_run: false 
      skip_report: false 
      max_concurrency: 1
      labels:
        preset-aws-ouzi: "true"
      trigger: "(?m)deploy-prow( please)?" 
      rerun_command: "deploy-prow"
      run_if_changed: '^(cluster/.*)$'
      branches:
        - master
      spec: 
        serviceAccountName: prow
        containers:
          - name: "deploy-prow"
            imagePullPolicy: IfNotPresent
            command:
              - make
            args:
              -  deploy
            image: quay.io/ouzi/toolbox:0.1.9
