presubmits:
  ouzi-dev/docs:
    # https://github.com/kubernetes/test-infra/blob/master/prow/inrepoconfig.md
    - name: validate-prow-yaml
      always_run: true
      decorate: true
      clone_uri: "git@github.com:ouzi-dev/docs.git"
      trigger: "(?m)validate-prow-yaml( please)?" 
      rerun_command: "validate-prow-yaml"
      extra_refs:
        - org: ouzi-dev
          repo: test-infra
          base_ref: master
      spec:
        tolerations:
          - effect: NoSchedule
            key: cloud.google.com/gke-preemptible
            operator: Equal
            value: "true"
        containers:
        - image: gcr.io/k8s-prow/checkconfig:v20220810-4ab15cddef
          command:
            - checkconfig
          args:
          - --plugin-config=../test-infra/prow/plugins.yaml
          - --config-path=../test-infra/prow/config.yaml
          - --prow-yaml-repo-name=$(REPO_OWNER)/$(REPO_NAME)
          - --exclude-warning=unknown-fields
    - name: validate-no-creds
      always_run: true
      decorate: true
      clone_uri: "git@github.com:ouzi-dev/docs.git"
      trigger: "(?m)validate-no-creds( please)?" 
      rerun_command: "validate-no-creds"
      spec:
        tolerations:
          - effect: NoSchedule
            key: cloud.google.com/gke-preemptible
            operator: Equal
            value: "true"
        containers:
        - image: quay.io/ouzi/git-secret-scanner:0.0.4
          command:
          - git-secrets
          args:
          - --scan