email: team@ouzi.dev
baseDomain: test-infra.ouzi.io
cluster:
  admin:
    group: team@ouzi.dev
github:
  org: ouzi-dev
  bot:
    username: ouzibot
certmanager:
  namespace: cert-manager
  svc_account:
    credstash:
      key: prow-cert-manager-svc-account-key
      table: credential-store
      version: "0000000000000000001"
oauth2Proxy:
  namespace: oauth-proxy
  clientid:
    credstash:
      key: prow-cluster-github-oauth-client-id
      table: credential-store
      version: "0000000000000000001"
  clientsecret:
    credstash:
      key: prow-cluster-github-oauth-client-secret
      table: credential-store
      version: "0000000000000000001"    
  cookiesecret:
    credstash:
      key: prow-cluster-github-oauth-cookie-secret
      table: credential-store
      version: "0000000000000000001"
externalDns:
  namespace: external-dns
  replicas: 1
nginxIngress:
  namespace: nginx-ingress
prow:
  namespace: prow
  namespaceForJobs: prow-test-pods
  prowbucketname: ouzidev-testinfra-252513-prow-artefacts
  credstashSecrets:
    - name: prow-bucket-gcs-credentials
      keys:
        - name: service-account.json
          key: prow-bucket-svc-account-key
          table: credential-store
          version: "0000000000000000001"
    - name: slack-token
      keys:
        - name: token
          key: ouzibot_slack_legacytoken
          table: credential-store
          version: "0000000000000000001"
    - name: github-token
      keys:
        - name: oauth
          key: github_bot_personal_access_token_prow
          table: credential-store
          version: "0000000000000000001"
    - name: github-ssh-key
      keys:
        - name: key
          key: github_bot_ssh_private_key
          table: credential-store
          version: "0000000000000000001"
    - name: oauth-config
      keys:
        - name: secret
          key: prow-oauth-config
          table: credential-store
          version: "0000000000000000001"

build:
  credstashSecrets:
    - name: gcs-credentials
      keys:
        - name: service-account.json
          key: prow-bucket-svc-account-key
          table: credential-store
          version: "0000000000000000001"
    - name: github-ssh-key
      keys:
        - name: key
          key: github_bot_ssh_private_key
          table: credential-store
          version: "0000000000000000001"
    - name: github-token
      keys:
        - name: oauth
          key: github_bot_personal_access_token_prow
          table: credential-store
          version: "0000000000000000001"
    - name: ouzi-bot-dockerconfig # needs to be applied manually as the credstash controller only creates a Opaque type secret unfortunately
      keys:
        - name: .dockerconfigjson
          key: quay_bot_dockerconfig
          table: credential-store
          version: "0000000000000000001"
    - name: aws-ouzi-creds
      keys:
      - name: access_key_id
        key: prow-aws-access-key-id
        table: credential-store
        version: "0000000000000000001"
      - name: secret_access_key
        key: prow-aws-secret-access-key
        table: credential-store
        version: "0000000000000000001"
# DMS
    - name: ouzidev-cannon-prow-gcloud-service-account
      keys:
        - name: service-account.json
          key: ouzidev-cannon-prow-gcloud-service-account
          table: singularity
          version: "0000000000000000001"
    - name: ouzidev-cannon-prow-gke-kubeconfig
      keys:
        - name: kubeconfig
          key: ouzidev-cannon-prow-gke-kubeconfig
          table: singularity
          version: "0000000000000000001"
    - name: aws-dms-creds
      keys:
      - name: access_key_id
        key: prow_dms_access_key_id
        table: singularity
        version: "0000000000000000001"
      - name: secret_access_key
        key: prow_dms_secret_access_key
        table: singularity
        version: "0000000000000000001"
# Singularity
    - name: ouzidev-hoarder-prow-gcloud-service-account
      keys:
        - name: service-account.json
          key: ouzidev-hoarder-prow-gcloud-service-account
          table: singularity
          version: "0000000000000000001"
    - name: ouzidev-hoarder-prow-gke-kubeconfig
      keys:
        - name: kubeconfig
          key: ouzidev-hoarder-prow-gke-kubeconfig
          table: singularity
          version: "0000000000000000001"
    - name: aws-4leaf-creds
      keys:
      - name: access_key_id
        key: prow_4leaf_access_key_id
        table: singularity
        version: "0000000000000000001"
      - name: secret_access_key
        key: prow_4leaf_secret_access_key
        table: singularity
        version: "0000000000000000001"
credstashOperator:
  namespace: credstash-operator
  aws:
    region: eu-west-1