## CredStash Secret Defaults
      # table: credential-store
      # version: "0000000000000000001"

# Global Settings
global:
  email: team@ouzi.dev
  admingroup: team@ouzi.dev
  basedomain: test-infra.ouzi.io
  gcloud:
    project: ouzidev-testinfra-252513
  github:
    org: ouzi-dev
    bot:
      username: ouzibot

# Cert-Manager settings 
certmanager:
  svcaccount:
    credstash:
      key: prow-cert-manager-svc-account-key
      table: credential-store
      version: "0000000000000000001"

# Oauth2 Proxy Settings
oauthproxy:
  clientid:
    credstash:
      key: prow-cluster-github-oauth-client-id
  clientsecret:
    credstash:
      key: prow-cluster-github-oauth-client-secret 
  cookiesecret:
    credstash:
      key: prow-cluster-github-oauth-cookie-secret

# Credstash Operator that will allow you to fetch secrets from Credstash
credstashoperator:
  instances:
    system:
      aws:
        region: eu-west-1
        # accessid: 1234567890
        # secretaccesskey: topsecret

# GKE PreEmptible Killer Settings
gkepreemptiblekiller:
  svcaccount:
    credstash:
      key: prow-gke-preemptible-killer-svc-account-key

# Prow Settings
prow:
  prowbucketname: ouzidev-testinfra-252513-prow-artefacts
  gcs:
    svcaccount:
      credstash:
        key: prow-bucket-svc-account-key
  slack:
    token:
      credstash:
        key: ouzibot_slack_legacytoken
  github:
    token:
      credstash:
        key: github_bot_personal_access_token_prow
    sshkey:
      credstash:
        key: github_bot_ssh_private_key
    oauthconfig:
      credstash:
        key: prow-oauth-config

# Build Secrets
buildsecrets:
  credstashsecrets:
    - name: gcs-credentials
      keys:
        - name: service-account.json
          key: prow-bucket-svc-account-key
    - name: github-ssh-key
      keys:
        - name: key
          key: github_bot_ssh_private_key
    - name: github-token
      keys:
        - name: oauth
          key: github_bot_personal_access_token_prow
# Ouzi
    - name: ouzi-bot-dockerconfig
      type: "kubernetes.io/dockerconfigjson"
      keys:
        - name: .dockerconfigjson
          key: quay_bot_dockerconfig
    - name: aws-ouzi-creds
      keys:
      - name: access_key_id
        key: terraform-aws-access-key-id
      - name: secret_access_key
        key: terraform-aws-secret-access-key
      - name: default_region
        key: terraform-aws-region
    - name: ouzidev-testinfra-prow-gcloud-service-account
      keys:
        - name: service-account.json
          key: prow-terraform-svc-account-key
    - name: ouzi-chart-museum-push-creds
      keys:
        - name: basic-auth-user
          key: chartmuseum-username
        - name: basic-auth-pass
          key: chartmuseum-password
# Singularity
    - name: ouzidev-hoarder-prow-gcloud-service-account
      keys:
        - name: service-account.json
          key: ouzidev-hoarder-prow-gcloud-service-account
          table: fourleaf
    - name: ouzidev-hoarder-prow-gke-kubeconfig
      keys:
        - name: kubeconfig
          key: ouzidev-hoarder-prow-gke-kubeconfig
          table: fourleaf
    - name: aws-4leaf-creds
      keys:
      - name: access_key_id
        key: prow_4leaf_access_key_id
        table: fourleaf
      - name: secret_access_key
        key: prow_4leaf_secret_access_key
        table: fourleaf