{{ $root := . -}}
{{ range .credstash -}}
---
apiVersion: credstash.local/v1
kind: CredStashSecret
metadata:
  name: {{ .name | quote }}
  namespace: {{ $root.namespaceForJobs }}
spec:
{{- range .keys }}
  - name: {{ .name }}
    from: {{ .key | quote }}
    table: {{ .table | quote }}
    version: {{ .version | quote }}
{{ end -}}
{{ end -}}
{{ $root := . -}}
{{ range .credstash -}}
---
apiVersion: credstash.ouzi.tech/v1alpha1
kind: CredstashSecret
metadata:
  name: {{ printf "%s-%s" .name "2" | quote }}
  namespace: {{ $root.namespaceForJobs }}
spec:
{{- range .keys }}
  - name: {{ .name }}
    from: {{ .key | quote }}
    table: {{ .table | quote }}
    version: {{ .version | quote }}
{{ end -}}
{{ end -}}