{{ $root := . -}}
{{ range .credstash -}}
---
apiVersion: credstash.ouzi.tech/v1alpha1
kind: CredstashSecret
metadata:
  name: {{ .name | quote }}
  namespace: {{ $root.namespaceForJobs }}
spec:
  secrets:
{{- range .keys }}
  - name: {{ .name }}
    key: {{ .key | quote }}
    table: {{ .table | quote }}
    version: {{ .version | quote }}
{{ end -}}
{{ end -}}