---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: nginx
  name: oauth2-proxy
  namespace: {{ .namespace }}
spec:
  rules:
  - host: {{ .host }}
    http:
      paths:
      - backend:
          serviceName: oauth2-proxy
          servicePort: http
        path: /
  tls:
    - hosts:
      - {{ .host }}
      secretName: oauth-tls