{{ $root := . -}}
{{ range .credstash -}}
---
apiVersion: credstash.local/v1
kind: CredStashSecret
metadata:
  name: {{ .name | quote }}
  namespace: {{ $root.namespace }}
spec:
{{- range .keys }}
  - name: {{ .name }}
    from: {{ .key | quote }}
    table: {{ .table | quote }}
    version: {{ .version | quote }}
{{ end -}}
{{ end -}}