presubmits:
  ouzi-dev/cannon-prow:
    # https://github.com/kubernetes/test-infra/blob/master/prow/inrepoconfig.md
    - name: validate-prow-yaml
      always_run: true
      decorate: true
      clone_uri: "git@github.com:ouzi-dev/cannon-prow.git"
      trigger: "(?m)validate-prow-yaml( please)?" 
      rerun_command: "validate-prow-yaml"
      extra_refs:
        - org: ouzi-dev
          repo: test-infra
          base_ref: master
      spec:
        containers:
        - image: gcr.io/k8s-prow/checkconfig:v20200131-19ad23dfd
          command:
          - /app/prow/cmd/checkconfig/app.binary
          args:
          - --plugin-config=../test-infra/prow/plugins.yaml
          - --config-path=../test-infra/prow/config.yaml
          - --prow-yaml-repo-name=$(REPO_OWNER)/$(REPO_NAME)
    - name: validate-no-creds
      always_run: true
      decorate: true
      clone_uri: "git@github.com:ouzi-dev/cannon-prow.git"
      trigger: "(?m)validate-no-creds( please)?" 
      rerun_command: "validate-no-creds"
      spec:
        containers:
        - image: quay.io/ouzi/git-secret-scanner:0.0.3
          command:
          - git-secrets
          args:
          - --scan
    - name: test-infra
      context: test-infra
      decorate: true 
      clone_uri: "git@github.com:ouzi-dev/cannon-prow.git"
      always_run: false 
      skip_report: false 
      max_concurrency: 1
      labels:
        preset-aws-dms: "true"
        preset-kubeconfig-cannon-prow: "true"
      trigger: "(?m)test-infra( please)?" 
      rerun_command: "test-infra"
      run_if_changed: '^(infrastructure/.*)$'
      spec: 
        containers:
          - name: "test-infra"
            imagePullPolicy: IfNotPresent
            command:
              - make
            args:
              - infra-setup
              - infra-plan
            image: quay.io/ouzi/toolbox:0.1.11
    - name: test-dmsengage-manifests
      context: test-dmsengage-manifests
      decorate: true 
      clone_uri: "git@github.com:ouzi-dev/cannon-prow.git"
      always_run: false 
      skip_report: false 
      max_concurrency: 1
      labels:
        preset-aws-dms: "true"
        preset-kubeconfig-cannon-prow: "true"
      trigger: "(?m)test-dmsengage-manifests( please)?" 
      rerun_command: "test-dmsengage-manifests"
      run_if_changed: '^(dmsengage/.*)$'
      spec: 
        containers:
          - name: "test-dmsengage-manifests"
            imagePullPolicy: IfNotPresent
            command:
              - make
            args:
              -  dmsengage-deploy-dry-run
            image: quay.io/ouzi/toolbox:0.1.11
postsubmits:
  ouzi-dev/cannon-prow:
    - name: apply-infra
      context: apply-infra
      decorate: true 
      clone_uri: "git@github.com:ouzi-dev/cannon-prow.git"
      always_run: false 
      skip_report: false 
      max_concurrency: 1
      branches:
        - master
      labels:
        preset-aws-dms: "true"
        preset-kubeconfig-cannon-prow: "true"
      trigger: "(?m)apply-infra( please)?" 
      rerun_command: "apply-infra"
      run_if_changed: '^(infrastructure/.*)$'
      spec: 
        containers:
          - name: "apply-infra"
            imagePullPolicy: IfNotPresent
            command:
              - make
            args:
              - TF_EXTRA_ARGS=--auto-approve
              - infra-setup
              - infra-apply
            image: quay.io/ouzi/toolbox:0.1.11
    - name: apply-dmsengage-manifests
      context: apply-dmsengage-manifests
      decorate: true 
      clone_uri: "git@github.com:ouzi-dev/cannon-prow.git"
      always_run: false 
      skip_report: false 
      max_concurrency: 1
      branches:
        - master
      labels:
        preset-aws-dms: "true"
        preset-kubeconfig-cannon-prow: "true"
      trigger: "(?m)apply-dmsengage-manifests( please)?" 
      rerun_command: "apply-dmsengage-manifests"
      run_if_changed: '^(dmsengage/.*)$'
      spec: 
        containers:
          - name: "apply-dmsengage-manifests"
            imagePullPolicy: IfNotPresent
            command:
              - make
            args:
              -  dmsengage-deploy
            image: quay.io/ouzi/toolbox:0.1.11
