---
apiVersion: credstash.ouzi.tech/v1alpha1
kind: CredstashSecret
metadata:
  name: clouddns-dns01-solver-svc-acct
  namespace: {{ .namespace }}
spec:
  secrets:
  - name: key.json
    key: {{ .credstash.svc_account_key | quote }}
    table: {{ .credstash.svc_account_table | quote }}
    version: {{ .credstash.svc_account_version | quote }}