apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: nginx-ingress
  name: nginx-ingress-controller
  namespace: monitoring
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 15s
    port: metrics
  jobLabel: app
  namespaceSelector:
    matchNames:
    - nginx
  selector:
    matchLabels:
      app: nginx-ingress