plugins:
  ouzi-dev/test-infra:
  - config-updater
  ouzi-dev:
    - approve  # Allow OWNERS to /approve
    - assign  # Allow /assign and /cc
    - blunderbuss  # Auto-assign people
    - cat # /meow replies with cat pictures
    - dog # /bark replies with dog pictures
    - help  # Support /help and /good-first-issue
    - hold  # Support /hold to delay merge
    - lgtm  # Allow /lgtm 
    - lifecycle  # Allow /lifecycle stale
    - override
    - size  # Auto-label size of PR
    - trigger  # Allow people to configure CI jobs to /test
    - verify-owners # Validates OWNERS file changes in PRs.
    - wip  # Auto-hold PRs with WIP in title
    - yuks # Let prow tell a /joke
    - branchcleaner
    - pony
    - shrug
    - skip
    - welcome
    - heart

config_updater:
  maps:
    prow/labels.yaml:
      name: label-config
    prow/config.yaml:
      name: config
    prow/plugins.yaml:
      name: plugins
    config/jobs/**/*.yaml:
      name: job-config
      gzip: true

triggers:
- repos:
  - ouzi-dev

approve:
- repos:
  - ouzi-dev
  require_self_approval: false
  lgtm_acts_as_approve: true

lgtm:
- repos:
  - ouzi-dev
  review_acts_as_lgtm: true

external_plugins:
  ouzi-dev:
  - name: needs-rebase
    events:
      - pull_request

welcome:
- repos:
  - ouzi-dev

blunderbuss:
  max_request_count: 2
  use_status_availability: true  

size:
  s:   10
  m:   30
  l:   100
  xl:  500
  xxl: 1000

slack:
  mergewarnings:
  - repos:
    - ouzi-dev
    channels:
    - prs
    whitelist:
    - k8s-ci-robot

